# Generated by Django 4.2 on 2023-04-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_option_four_poll_option_four_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_five',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_five_count',
            field=models.IntegerField(default=0),
        ),
    ]
