# Generated by Django 4.2 on 2023-05-08 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_option_five_poll_option_five_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='current_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
