# Generated by Django 4.2 on 2023-05-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_current_time_poll_poll_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='current_time',
            new_name='start_time',
        ),
    ]
